function Config(){}

Config.HARD_RANGE = 5;
Config.STEP_BONUS_PER_HARD = 20;
Config.LEGEND_LVL_BONUS_SUM = 200;
Config.XP_PER_LVL = 1000;
Config.NEWS_DEMON_TIME = 180000;
Config.FAST_DEMON_TIME = 60000;
Config.VERIFY_DEMON_TIME = 60000;
Config.VERIFY_REQUIRED_TIME = 300000;
Config.UPDATE_DEMON_TIME = 600000;		

Config.DEFAULT_LIKE_LIMIT = 40;
Config.DEFAULT_SUBSCRIBE_LIMIT = 35;

Config.AUTO_TASK_DEMON_TIME = 180000;
Config.AUTO_TASK_DEMON_TG_TIME = 120000;		//trubo_green
Config.AUTO_TASK_DEMON_TB_TIME = 90000;			//trubo_blue
Config.AUTO_TASK_DEMON_TR_TIME = 60000;			//trubo_red
Config.AUTO_TASK_DEMON_TD_TIME = 30000;			//trubo_dark

Config.LIMIT_REFERAL_MIN = 200;
Config.REFERAL_PERCENT = 10;
Config.STAY_REFERAL_BONUS = 200;

Config.MIN_TOTAL_LIKES = 20;
Config.MIN_POSTS = 4;
Config.MIN_FOLLOWED = 20;

Config.SUBSCRIBE_SETTING = "subscribe";
Config.AUTOEARN_SETTING = "autoearn";
Config.FIRSTTIME_SETTING = "firsttime";
Config.NOTIFICATION_SETTING = "notifvolume";
Config.NOTIFICATION_ACTIVE_SETTING = "notifactivate";
Config.AUTO_TASK_SETTING = "autotaskmode";
Config.AUTO_TASK_LIMIT_SETTING = "autotasklimit";

Config.SETTINGS = [Config.SUBSCRIBE_SETTING, Config.AUTOEARN_SETTING, Config.FIRSTTIME_SETTING,
				   Config.NOTIFICATION_SETTING, Config.NOTIFICATION_ACTIVE_SETTING, Config.AUTO_TASK_SETTING, Config.AUTO_TASK_LIMIT_SETTING];

Config.MAIN_TUTORIAL = 1;
Config.BID_TUTORIAL = 2;
Config.EARN_TUTORIAL = 3;
Config.REFERRAL_TUTORIAL = 4;
Config.TUTORIALS = [Config.MAIN_TUTORIAL, Config.BID_TUTORIAL, Config.EARN_TUTORIAL, Config.REFERRAL_TUTORIAL];

Config.SUBSCRIBE_VALUE = 0;
Config.AUTOEARN_VALUE = 1;
Config.FIRSTTIME_VALUE = 1;
Config.NOTIFICATION_VALUE = 1;
Config.DEFAULT_NOTIFICATION_ACTIVE_VALUE = 1;
//0 - off, 1 - likes, 2 - likes + subscribes
Config.AUTO_TASK_VALUE = 0;
Config.AUTO_TASK_LIMIT_VALUE = 0;
Config.DEF_VALUES = [Config.SUBSCRIBE_VALUE, Config.AUTOEARN_VALUE, Config.FIRSTTIME_VALUE,
					 Config.NOTIFICATION_VALUE, Config.DEFAULT_NOTIFICATION_ACTIVE_VALUE, Config.AUTO_TASK_VALUE, Config.AUTO_TASK_LIMIT_VALUE];	//default vaues for settings

